In [1]:
import numpy as np #np라는 별칭으로 numpy를 불러서 사용하겠다.

In [6]:
num = [1,2,3,4,5,6,7,8,9]
# result = num + [3]
result = num * 2
result

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
arr = np.array(num)
arr + 3 # = arr + np.array([3])

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
new_num = []
for i in num:
  new_num.append(i+3)
new_num

[4, 5, 6, 7, 8, 9, 10, 11, 12]

In [14]:
new_num = [i+3 for i in num]#리스트 컴프레이션
new_num

[4, 5, 6, 7, 8, 9, 10, 11, 12]

In [21]:
import time

num = range(10000)
result = []
start = time.time()
for i in num:
  i += 3
  result.append(i)
end = time.time()
sec = (end - start) * 1000
print(f"{sec: .4f} sec")
print(result[-5:])

 1.6849 sec
[9998, 9999, 10000, 10001, 10002]


In [29]:
import time
import numpy as np

num = np.arange(10000)
start = time.time()
result = num + 3
end = time.time()
sec = (end - start) * 1000
print(f"{sec: .5f} sec")
print(result[-5:])

 0.11706 sec
[ 9998  9999 10000 10001 10002]


In [30]:
text = ['I','Love','Python']
text2 = ['(나)','(좋아해)','(파이썬)']

result = text + text2
result

['I', 'Love', 'Python', '(나)', '(좋아해)', '(파이썬)']

In [31]:
import numpy as np

arr_str = np.array(['I','Love','Python'],dtype=object)
arr_str2 = np.array(['(나)','(좋아해)','(파이썬)'])

result = arr_str + arr_str2
result

array(['I(나)', 'Love(좋아해)', 'Python(파이썬)'], dtype=object)

In [33]:
import numpy as np

arr = np.array([[1,2]])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[1, 2]])

In [37]:
import numpy as np

arr = np.array([[0,0,0],
								[1,1,1]])
arr

array([[0, 0, 0],
       [1, 1, 1]])

In [38]:
print(arr.ndim) # 차원수
print(arr.shape) # array의 모양
print(type(arr)) # class
print(arr.dtype) # 요소들의 Type

2
(2, 3)
<class 'numpy.ndarray'>
int64


In [40]:
import numpy as np

arr = np.array([1,2,3])
# arr2 = np.array([1,2,3], float)
# print(arr.dtype, arr2.dtype)
# arr.astype(float)
arr.dtype

dtype('int64')

In [41]:
arr2 = np.array([1,2,3], float)
arr2.dtype

dtype('float64')

In [42]:
arr3 = np.array([1,2,3], str)
arr3.dtype

dtype('<U1')

In [49]:
arr3.astype("int64")
arr3.dtype

dtype('<U1')

In [50]:
arr4 = arr3.astype("int64")
arr4.dtype

dtype('int64')

In [245]:
zer = np.zeros(2)
zer2 = np.zeros((3,2))
zer3 = np.zeros((2,3,2))
print(zer)
print('--------------------')
print(zer2)
print('--------------------')
print(zer3)

[0. 0.]
--------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]
--------------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [52]:
ful = np.full((2),5)
ful2 = np.full((2,3),5)
ful3 = np.full((2,3,4), 'full')
print(ful)
print('--------------------')
print(ful2)
print('--------------------')
print(ful3 )

[5 5]
--------------------
[[5 5 5]
 [5 5 5]]
--------------------
[[['full' 'full' 'full' 'full']
  ['full' 'full' 'full' 'full']
  ['full' 'full' 'full' 'full']]

 [['full' 'full' 'full' 'full']
  ['full' 'full' 'full' 'full']
  ['full' 'full' 'full' 'full']]]


In [56]:
arn = np.arange(8)
arn2 = np.arange(2,4) # 시작, 끝
arn3 = np.arange(5,10,2)
print(arn)
print('--------------------')
print(arn2)
print('--------------------')
print(arn3)

[0 1 2 3 4 5 6 7]
--------------------
[2 3]
--------------------
[5 7 9]


In [54]:
lin = np.arange(2,8)
lin2 = np.linspace(3,7,10)

print(lin)
print('--------------------')
print(lin2)

[2 3 4 5 6 7]
--------------------
[3.         3.44444444 3.88888889 4.33333333 4.77777778 5.22222222
 5.66666667 6.11111111 6.55555556 7.        ]


In [57]:
iden = np.identity(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [251]:
eye = np.eye(3)
eye2 = np.eye(3,k=-1)
eye3 = np.eye(3,5)

print(eye)
print('--------------------')
print(eye2)
print('--------------------')
print(eye3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
--------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [62]:
import numpy as np

arr = np.array([1,2,3])

print(arr[1])
print(arr[0:2])
print(arr[1:])
print(arr[-2:])

2
[1 2]
[2 3]
[2 3]


In [63]:
li = [[1,2,3],[4,5,6]]

In [64]:
print(li[0][1:])

[2, 3]


In [65]:
arr = np.array(li)

In [67]:
arr[0][1:]

array([2, 3])

In [68]:
arr[0,1:]

array([2, 3])

In [69]:
li = [1,2,3,4,5,6,7,8,9,10,11,12]

In [75]:
#짝수만 찾아주세요
result = []
for i in li:
  if i % 2 == 0:
    result.append(i)
result

[2, 4, 6, 8, 10, 12]

In [77]:
li[1::2]

[2, 4, 6, 8, 10, 12]

In [94]:
li2 = [[4,1,3,2],[7,6,8,5],[9,10,11,12]]

In [95]:
result = []
for j in li2:
  for i in j:
    if i % 2 == 0:
      result.append(i)
result

[4, 2, 6, 8, 10, 12]

In [97]:
arr = np.array(li2)
arr

array([[ 4,  1,  3,  2],
       [ 7,  6,  8,  5],
       [ 9, 10, 11, 12]])

In [98]:
arr[arr % 2 == 0]
arr[arr < 5]

array([4, 1, 3, 2])

In [102]:
arr % 2 == 0

array([[ True, False, False,  True],
       [False,  True,  True, False],
       [False,  True, False,  True]])

In [106]:
arr.shape

(3, 4)

In [111]:
arr.reshape((6,2))

array([[ 4,  1],
       [ 3,  2],
       [ 7,  6],
       [ 8,  5],
       [ 9, 10],
       [11, 12]])

In [112]:
arr.shape

(3, 4)

In [115]:
arr.resize(2,6)
arr

array([[ 4,  1,  3,  2,  7,  6],
       [ 8,  5,  9, 10, 11, 12]])

In [116]:
arr

array([[ 4,  1,  3,  2,  7,  6],
       [ 8,  5,  9, 10, 11, 12]])

In [124]:
arr.resize(5, 5, refcheck=False)# 요소가 25개 필요
arr

array([[ 4,  1,  3,  2,  7],
       [ 6,  8,  5,  9, 10],
       [11, 12,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [123]:
arr.reshape(5,5,-1)

array([[[ 4],
        [ 1],
        [ 3],
        [ 2],
        [ 7]],

       [[ 6],
        [ 8],
        [ 5],
        [ 9],
        [10]],

       [[11],
        [12],
        [ 0],
        [ 0],
        [ 0]],

       [[ 0],
        [ 0],
        [ 0],
        [ 0],
        [ 0]],

       [[ 0],
        [ 0],
        [ 0],
        [ 0],
        [ 0]]])

In [93]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[arr<5])

print(arr[arr%2==0])

print(arr[(arr > 2) & (arr < 11)])

five_up = ( arr > 5 ) | (arr == 5)
print(five_up)

print(arr[five_up])

[1 2 3 4]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]


In [127]:
arr = np.array([[1,2],[3,4],[5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [131]:
arr_re = arr.reshape((2,3)) # reshape는 모양만 바꿔줌.
arr_re

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
arr.T # transpose(전체행렬)

array([[1, 3, 5],
       [2, 4, 6]])

In [133]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [143]:
zr = np.zeros((2,3,4,5))
zr

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [137]:
zr.shape

(2, 3, 4, 5)

In [138]:
zr.T.shape

(5, 4, 3, 2)

In [140]:
zr.transpose(3,0,2,1).shape

(5, 2, 4, 3)

In [142]:
zr.swapaxes(2,3).shape

(2, 3, 5, 4)

In [187]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
c = np.array([[5],[6]])
d = np.array([[5,6]])
print(a+b)
#numpy에서는 list에서 더하던 방식처럼 더해지지 않는다.

[[ 6  8]
 [ 8 10]]


In [177]:
a.shape

(2, 2)

In [178]:
b.shape

(1, 2)

In [185]:
b

array([[5, 6]])

In [179]:
c.shape

(2, 1)

In [164]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [188]:
np.concatenate((b,d), axis=0)

array([[5, 6],
       [5, 6]])

In [172]:
np.concatenate((a,c), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
#축 차원 dmensional

In [190]:
s = np.array([[1,2],[3,4],[5,6]])


In [192]:
s.sum()# 단항 연산

21

In [193]:
s.sum(axis = 0) # 축 연산

array([ 9, 12])

In [195]:
import numpy as np

arr = np.array(np.arange(1,11))

print(arr)
print(arr.sum())

print(arr.cumsum())


[ 1  2  3  4  5  6  7  8  9 10]
55
[ 1  3  6 10 15 21 28 36 45 55]


In [196]:
arr = np.array(np.arange(1,11)).reshape(2,5)
print(arr)
print('---------------')
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print('---------------')
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
---------------
[ 7  9 11 13 15]
[15 40]
---------------
[[ 1  2  3  4  5]
 [ 7  9 11 13 15]]
[[ 1  3  6 10 15]
 [ 6 13 21 30 40]]


In [213]:
import numpy as np

arr = np.array(np.random.randint(1,10,5))
arr

array([3, 7, 5, 9, 5])

In [214]:
print(arr.max())

9


In [215]:
print(arr.min())

3


In [224]:
arr = np.array(np.arange(1,11)).reshape(2,5)
print(arr)
print('---------------')
print(arr.min(axis=0))
print(arr.min(axis=1))
print('---------------')
print(arr.max(axis=0))
print(arr.max(axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
---------------
[1 2 3 4 5]
[1 6]
---------------
[ 6  7  8  9 10]
[ 5 10]


In [227]:
import numpy as np

arr = np.array([1,2,3,2,2,4,5,5,5])
np.unique(arr)
np.unique(arr, return_counts=True)


(array([1, 2, 3, 4, 5]), array([1, 3, 1, 1, 3]))

In [228]:
np.unique(arr, return_counts=False)

array([1, 2, 3, 4, 5])

In [229]:
import numpy as np

arr = np.array([1,5,2,3,7,8,9,4])

arr_a = np.sort(arr)
arr_d = np.sort(arr)[::-1]
print(arr_a)
print(arr_d)

[1 2 3 4 5 7 8 9]
[9 8 7 5 4 3 2 1]


In [237]:
arr = np.array([1,5,9,2,7,8,3,4]).reshape(2,4)

arr_c = np.sort(arr, axis=0)
arr_r = np.sort(arr, axis=1)

In [240]:
print(arr_c)

[[1 5 3 2]
 [7 8 9 4]]


In [238]:
print(arr_r)

[[1 2 5 9]
 [3 4 7 8]]


In [241]:
np.random.choice(np.arange(1,11), size = 5, replace = False)

array([6, 3, 8, 9, 5])